import superjson from 'superjson';
import {useEffect,useState,useSyncExternalStore} from 'react';
import type {BrandApiHooks,QueryHook,MutationHook,CachePort,QueryOptions,QueryResult} from '../module/client/api-hooks';
export type RpcCall=(path:string,input:unknown,mutation:boolean)=>Promise<unknown>;
export const liveRpc:RpcCall=async(path,input,mutation)=>{
 const payload=superjson.serialize(input);const encoded=JSON.stringify(payload);
 const response=await fetch(`/api/trpc/${path}${mutation?'':`?input=${encodeURIComponent(encoded)}`}`,{credentials:'same-origin',method:mutation?'POST':'GET',headers:mutation?{'Content-Type':'application/json'}:undefined,body:mutation?encoded:undefined});
 const result=await response.json();const failure=result.error?.json??result.error;
 if(!response.ok||failure)throw new Error(failure?.message??`请求失败（${response.status}）`);
 if(!result.result?.data)throw new Error('业务接口返回格式错误');return superjson.deserialize(result.result.data);
};
export function createBrandApi(call:RpcCall){
 type State<T>={data:T|undefined;error:Error|null;isLoading:boolean;isFetching:boolean;isError:boolean;isSuccess:boolean};
 const entries=new Map<string,{refetch():Promise<unknown>;notify():void;state:State<unknown>}>();
 function resource<I,O>(path:string,input:I){const key=JSON.stringify([path,input]);const old=entries.get(key);if(old)return old as ReturnType<typeof create<O>>;return create<O>();function create<T>(){const listeners=new Set<()=>void>();let pending:Promise<{data:T|undefined;error?:Error}>|undefined;
  const record={state:{data:undefined,error:null,isLoading:true,isFetching:false,isError:false,isSuccess:false} as State<T>,subscribe(fn:()=>void){listeners.add(fn);return()=>{listeners.delete(fn);};},notify(){listeners.forEach(fn=>fn());},refetch(){if(pending)return pending;record.state={...record.state,isFetching:true};record.notify();pending=(async()=>{try{const data=await call(path,input,false) as T;record.state={data,error:null,isLoading:false,isFetching:false,isError:false,isSuccess:true};return {data};}catch(error){const cause=error instanceof Error?error:new Error(String(error));record.state={...record.state,error:cause,isLoading:false,isFetching:false,isError:true,isSuccess:false};return {data:record.state.data,error:cause};}finally{pending=undefined;record.notify();}})();return pending;}};entries.set(key,record);return record;}}
 function query<I,O>(path:string):QueryHook<I,O>&CachePort<I,O>{return {useQuery(input,options){const entry=resource<I,O>(path,input);const state=useSyncExternalStore(entry.subscribe,()=>entry.state);const interval=typeof options?.refetchInterval==='function'?options.refetchInterval({state}):options?.refetchInterval;useEffect(()=>{if(options?.enabled===false)return;void entry.refetch();const focus=()=>void entry.refetch();if(options?.refetchOnWindowFocus)window.addEventListener('focus',focus);return()=>window.removeEventListener('focus',focus);},[entry,options?.enabled,options?.refetchOnWindowFocus]);useEffect(()=>{if(options?.enabled===false||!interval)return;const timer=window.setInterval(()=>{if(options?.refetchIntervalInBackground||!document.hidden)void entry.refetch();},interval);return()=>window.clearInterval(timer);},[entry,interval,options?.enabled,options?.refetchIntervalInBackground]);return {...state,refetch:entry.refetch};},async invalidate(){await Promise.all([...entries].filter(([key])=>JSON.parse(key)[0]===path).map(([,entry])=>entry.refetch()));},async cancel(){},async fetch(input){return await call(path,input,false) as O;},setData(input,update){const entry=resource<I,O>(path,input);entry.state={...entry.state,data:update(entry.state.data)};entry.notify();}};}
 function mutation<I,O>(path:string):MutationHook<I,O>{return {useMutation(options){const [state,setState]=useState<{data?:O;isPending:boolean;error:Error|null}>({isPending:false,error:null});async function mutateAsync(input:I){setState({isPending:true,error:null});try{const data=await call(path,input,true) as O;setState({data,isPending:false,error:null});options?.onSuccess?.(data);return data;}catch(error){const cause=error instanceof Error?error:new Error(String(error));setState({isPending:false,error:cause});throw cause;}}return {...state,mutateAsync,mutate(input){void mutateAsync(input).catch(()=>{});},reset(){setState({isPending:false,error:null});}};}};}
 const knowledge=query<void,{snapshot:import('../module/client/components/KnowledgeBaseViewer').KnowledgeSnapshotView|null}>('workspace.knowledge');
 const progress=query<void|{conversationId:string},{progress:import('../module/contracts/knowledge-base-public-progress').KnowledgeBaseProgressDto|null}>('workspace.knowledgeProgress');
 const reset=query<void,import('../module/client/api-hooks').KnowledgeResetStatus>('workspace.knowledgeReset.status');
 const keyword=query<void,import('../module/client/api-hooks').KeywordObservation>('workspace.brandQuestionUniverse.observe');
 const dashboard=query<void,{revision:number;payload?:{keywordTables:import('../module/client/dashboard/ManagedKeywordTables').ManagedKeywordTable[]}|null}>('workspace.dashboard');
 const api:BrandApiHooks={workspace:{knowledge,knowledgeProgress:progress,knowledgeReset:{status:reset,reset:mutation('workspace.knowledgeReset.reset')},brandQuestionUniverse:{observe:keyword,start:mutation('workspace.brandQuestionUniverse.start')},siteOps:{open:mutation('workspace.siteOps.open'),observe:query('workspace.siteOps.observe'),actFast:mutation('workspace.siteOps.actFast'),sendMessage:mutation('workspace.siteOps.sendMessage'),aliyunConnection:{beginOAuth:mutation('workspace.siteOps.aliyunConnection.beginOAuth'),listDomains:query('workspace.siteOps.aliyunConnection.listDomains'),disconnect:mutation('workspace.siteOps.aliyunConnection.disconnect')}}},useUtils:()=>({workspace:{knowledge:{invalidate:knowledge.invalidate,clear:()=>knowledge.setData(undefined,current=>current?{...current,snapshot:null}:current)},knowledgeProgress:progress,knowledgeReset:{status:reset},brandQuestionUniverse:{observe:keyword},dashboard,portal:{invalidate:async()=>{}}}})};
 return {api,dashboard};
}
