import {AgentWorkbenchShell} from "@frontmind/module-ui/components/AgentWorkbenchShell";
import {createContext,useContext,useEffect,useRef,type ReactNode} from 'react';
import {toast} from 'sonner';
import {configureBrandHost,type BrandHost,type WorkspaceRestOperation,type DraftGuard} from '../module/client/host';
import {createBrandConversationRuntime,type BrandConversationClient} from '../module/client/conversation-runtime';
import KnowledgeConversation,{KnowledgeComposer} from '../module/client/components/KnowledgeConversation';
import EnterpriseQaConversation from '../module/client/EnterpriseQaConversation';
import type {ModuleContext} from '../module/client/ModuleWorkspace';
import {reconcileKnowledgeBaseObservation} from '../module/client/lib/knowledge-progress';
const Purpose=createContext<'knowledge'|'enterprise_qa'>('knowledge');
export function ConversationPurposeProvider({children}:{children:ReactNode}){return <Purpose.Provider value="enterprise_qa">{children}</Purpose.Provider>;}
async function json<T>(path:string,init:RequestInit={}):Promise<T>{const response=await fetch(path,{credentials:'same-origin',...init});const result=await response.json();if(!response.ok)throw new Error(result.message??result.error??`读取失败（${response.status}）`);return result;}
export const liveConversations:BrandConversationClient={list:async purpose=>(await json<{conversations:Awaited<ReturnType<BrandConversationClient['list']>>}>(`/api/brand/conversations?purpose=${purpose}`)).conversations,sync:async(purpose,conversations,deletedIds)=>{await json('/api/brand/conversations/sync',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({purpose,conversations,deletedIds})});},observe:(conversationId,signal)=>reconcileKnowledgeBaseObservation({conversationId},signal)};
export function installBrandHost(context:ModuleContext,client:BrandConversationClient,preview:boolean){
 const knowledge=createBrandConversationRuntime(client,'knowledge',context.workspace.id);const qa=createBrandConversationRuntime(client,'enterprise_qa',context.workspace.id);const drafts=new Map<object,DraftGuard>();
 function rest(signal?:AbortSignal|null):WorkspaceRestOperation{const active=signal??new AbortController().signal;const assertActive=()=>{if(active.aborted)throw new DOMException('操作已取消','AbortError');};return {signal:active,assertActive,headers:extra=>({...extra}),async fetch(input,init={},implementation=fetch){assertActive();if(preview)throw new Error('本地预览不连接真实业务 API');const response=await implementation(input,{...init,credentials:'same-origin',signal:active});assertActive();return response;}};}
 const host:BrandHost={useRuntimeContext:()=>({workspaceId:context.workspace.id,accountId:context.workspace.ownerUserId,enabled:true}),useConversation:()=>useContext(Purpose)==='enterprise_qa'?qa.useConversation():knowledge.useConversation(),captureWorkspaceRestOperation:signal=>rest(signal),forkWorkspaceRestOperation:(_operation,signal)=>rest(signal),activateWorkspaceUploadScope:()=>()=>{},projectResourceUrl:path=>path,projectWorkspaceUrl:path=>path,deliveryProjectHeaders:extra=>({...extra}),useWorkspaceDraftGuard(input){const key=useRef({});useEffect(()=>{drafts.set(key.current,input);return()=>{drafts.delete(key.current);};},[input.dirty,input.label,input.save,input.discard]);useEffect(()=>{const guard=(event:BeforeUnloadEvent)=>{if([...drafts.values()].some(item=>item.dirty)){event.preventDefault();event.returnValue='';}};window.addEventListener('beforeunload',guard);return()=>window.removeEventListener('beforeunload',guard);},[]);},getUnsavedWorkspaceDrafts:()=>[...drafts.values()].filter(item=>item.dirty),requestWorkspaceNavigation(action){if(![...drafts.values()].some(item=>item.dirty)||window.confirm('尚有未保存的输入，确定离开当前页面？'))action();},showAiBillingAction:()=>false,Home:props=>props.purpose==='enterprise_qa'?<EnterpriseQaConversation {...props} preview={preview}/>:<KnowledgeConversation {...props}/>,ChatInput:KnowledgeComposer,AgentWorkbenchShell:props=><AgentWorkbenchShell {...props} requestNavigation={action=>host.requestWorkspaceNavigation(action)}/>,ProjectAgentWorkbench:({children})=><ConversationPurposeProvider><EnterpriseQaConversation preview={preview}/>{children}</ConversationPurposeProvider>,ConversationPurposeProvider,useBusinessWorkspace:()=>({isWorkbench:false,taskId:null,agentId:'brand',setSummary:()=>{}}),useBusinessWorkspaceSummary:()=>{},notifyUsageChanged:()=>{}};
 configureBrandHost(host);return {dispose(){knowledge.dispose();qa.dispose();}};
}
