/** Public data projections consumed by business code; storage and ownership enforcement are injected by the private Core. */
export type ConversationTurn = {
  enterpriseProjectId: string | null;
  id: string;
  conversationId: string;
  userId: number;
  createdAt: Date;
  updatedAt: Date;
  apiCredentialId: string | null;
  status: "running" | "completed" | "failed" | "cancelled" | "queued";
  upstreamTaskId: string | null;
  startedAt: Date | null;
  completedAt: Date | null;
  clientRequestId: string;
  buildId: string | null;
  errorCode: string | null;
  errorMessage: string | null;
  operationType: string | null;
  requestHash: string | null;
  leaseExpiresAt: Date | null;
  buildGeneration: number | null;
  operationKey: string | null;
  expectedRevision: number | null;
  expectedLeafId: string | null;
  upstreamIdempotencyKeyHash: string | null;
  attachmentFileIds: string[];
  metadata: Record<string, unknown>;
  model: string | null;
};
export type LocalAsset = {
  enterpriseProjectId: string | null;
  id: string;
  createdAt: Date;
  siteOpsKnowledgeInputEpochId: string | null;
  contentSha256: string;
  storageKey: string;
  sizeBytes: number;
  filename: string;
  mimeType: string;
  scope: "managed_user" | "website_frontend";
  accountUserId: number | null;
  presalesProjectId: string | null;
  storageKeyHash: string;
  refCount: number;
  retainUntil: Date | null;
};

export type MessageMetadata = {
  upstreamOutputId?: string;
  outputFiles?: Array<{ fileUrl: string; fileName: string; mimeType: string }>;
  inlineImages?: Array<{ src: string; alt?: string }>;
  elapsedTime?: number;
  responseStartedAt?: number;
  intermediateSteps?: unknown[];
  stepGroups?: unknown[];
  isStepsPlaceholder?: boolean;
  modelName?: string;
  [key: string]: unknown;
};

export type Conversation = {
  enterpriseProjectId: string | null;
  id: string;
  userId: number;
  createdAt: Date;
  updatedAt: Date;
  apiCredentialId: string | null;
  version: number;
  status: "idle" | "running" | "pending" | "awaiting_input" | "completed" | "error" | "failed" | "archived";
  deletedAt: Date | null;
  projectAssignmentId: string | null;
  title: string;
  upstreamTaskId: string | null;
  previousResponseId: string | null;
  taskUrl: string | null;
  lastKnownOutputLength: number;
  deletedMessageIds: string[];
  startedAt: Date | null;
  completedAt: Date | null;
};
export type Message = {
  id: string;
  userId: number;
  role: "user" | "assistant" | "system" | "tool";
  createdAt: Date;
  updatedAt: Date;
  deletedAt: Date | null;
  conversationId: string;
  turnId: string | null;
  metadata: MessageMetadata | null;
  content: string;
  sequence: number;
  sentAt: Date;
};
export type ProviderFileLease = {
  id: string;
  createdAt: Date;
  updatedAt: Date;
  apiCredentialId: string;
  credentialVersion: number;
  localAssetId: string;
  providerFileId: string | null;
  providerRequestId: string | null;
  uploadState: "failed" | "reserved" | "outcome_unknown" | "uploading" | "uploaded" | "expired";
  uploadedBytes: number;
  expiresAt: Date | null;
};
export type UpstreamResource = {
  enterpriseProjectId: string | null;
  id: string;
  userId: number;
  createdAt: Date;
  apiCredentialId: string;
  projectAssignmentId: string | null;
  conversationId: string | null;
  kind: "task" | "file";
  upstreamId: string;
  uploadedAt: Date | null;
  contentExpiresAt: Date | null;
  contentDeletedAt: Date | null;
};
